<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\StudyHub.Shared\StudyHub.Shared.csproj" />
    <ProjectReference Include="..\..\Logic\StudyHub.Logic.Domain\StudyHub.Logic.Domain.csproj" />
    <ProjectReference Include="..\..\Logic\StudyHub.Logic.Integration\StudyHub.Logic.Integration.csproj" />
    <ProjectReference Include="..\..\Data\StudyHub.Data\StudyHub.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
