<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\StudyHub.Shared\StudyHub.Shared.csproj" />
    <ProjectReference Include="..\..\Shared\StudyHub.Shared.Domain\StudyHub.Shared.Domain.csproj" />
    <ProjectReference Include="..\StudyHub.Logic.Domain.Contract\StudyHub.Logic.Domain.Contract.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
