<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\StudyHub.Shared\StudyHub.Shared.csproj" />
    <ProjectReference Include="..\..\Logic\StudyHub.Logic.Business\StudyHub.Logic.Business.csproj" />
    <ProjectReference Include="..\..\Infrastructure\StudyHub.Infrastructure\StudyHub.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Data\StudyHub.Data\StudyHub.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.6.0" />
  </ItemGroup>

</Project>
