namespace StudyHub.Shared.PracticeExams;

/// <summary>
/// A stored practice exam generated by AI. Exactly one of <see cref="CourseId"/> and
/// <see cref="DeckId"/> is set, matching <see cref="SourceKind"/>.
/// </summary>
public sealed record PracticeExam(
    Guid Id,
    string Title,
    PracticeExamLevel Level,
    int DurationMinutes,
    PracticeExamSourceKind SourceKind,
    Guid? CourseId,
    Guid? DeckId,
    string Model,
    string PromptVersion,
    string? FocusHint,
    bool IsArchived,
    DateTime CreatedAt,
    DateTime UpdatedAt
)
{
    public const int TitleMaxLength = 200;
    public const int ModelMaxLength = 100;
    public const int PromptVersionMaxLength = 50;
}
